version: '2.1'

services:

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recipe_db
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  postgres-init:
    image: postgres:13
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGPASSWORD=postgres
    volumes:
      - ./database-init/schema.sql:/schema.sql
      - ./database-init/initialize-imdb.sh:/initialize-imdb.sh
    command: bash -c "sleep 10 && chmod u+x /initialize-imdb.sh && /initialize-imdb.sh"


